# Generated by Django 3.2.8 on 2021-11-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0001_initial'),
    ]

    operations = [

    ]
