# Generated by Django 3.2.8 on 2021-10-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0002_alter_notes_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='pub_date',
        ),
    ]
