# Generated by Django 3.2.8 on 2021-10-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0003_remove_notes_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
