# Generated by Django 3.2.8 on 2021-10-19 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0005_alter_notes_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
