# Generated by Django 3.2.8 on 2021-10-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0006_notes_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='timestamp',
        ),
    ]
