# Generated by Django 3.2.8 on 2021-10-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0007_remove_notes_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_text',
            field=models.TextField(max_length=400),
        ),
    ]
