# Generated by Django 3.2.8 on 2021-10-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0008_auto_20211020_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password1', models.CharField(max_length=15)),
                ('password2', models.CharField(max_length=15)),
            ],
        ),
    ]
