# Generated by Django 3.2.8 on 2021-10-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
