# Generated by Django 3.2.8 on 2021-10-22 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0015_auto_20211022_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 5, 34, 39405)),
        ),
    ]
