# Generated by Django 3.2.8 on 2021-10-22 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0016_alter_product_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 33, 40, 877706)),
        ),
    ]
