# Generated by Django 3.2.8 on 2021-10-22 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0019_auto_20211022_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 59, 19, 201844)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 21, 59, 19, 201844)),
        ),
    ]
