# Generated by Django 3.2.8 on 2021-10-23 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0026_auto_20211022_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(choices=[('Qizil', 'Qizil'), ('Yashil', 'Yashil'), ('Qora', 'Qora')], default=('Qizil', 'Qizil'), max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_season',
            field=models.CharField(choices=[('Qishki', 'Qishki'), ('Yozgi', 'Yozgi'), ('Kuzgi', 'Kuzgi'), ('Bahorgi', 'Bahorgi'), ('Kuzgi va bahorgi', 'Kuzgi va bahorgi')], default=('Kuzgi va bahorgi', 'Kuzgi va bahorgi'), max_length=25),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default=('M', 'M'), max_length=5),
        ),
        migrations.AlterField(
            model_name='notes',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 2, 42, 56, 228037)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 2, 42, 56, 228037)),
        ),
    ]
