# Generated by Django 3.2.8 on 2021-10-23 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0028_auto_20211023_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 3, 0, 51, 11843)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 3, 0, 51, 11843)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.CharField(choices=[('', 'Qizil'), ('', 'Yashil'), ('', 'Qora')], default=('', 'Qizil'), max_length=15),
        ),
    ]
