# Generated by Django 3.2.8 on 2021-10-23 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0029_auto_20211023_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 3, 3, 53, 311852)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 3, 3, 53, 311852)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.CharField(choices=[('Qizil', 'Qizil'), ('Yashil', 'Yashil'), ('Qora', 'Qora')], default=('Qizil', 'Qizil'), max_length=15),
        ),
    ]
