# Generated by Django 3.2.8 on 2021-10-23 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0031_auto_20211023_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 20, 56, 10, 242485)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 20, 56, 10, 242485)),
        ),
    ]
