# Generated by Django 3.2.8 on 2021-10-23 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0032_auto_20211023_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 21, 8, 37, 139365)),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
