# Generated by Django 3.2.8 on 2021-10-23 21:49

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0035_auto_20211023_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 21, 49, 51, 555718)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 21, 49, 51, 555718)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Qizil', 'Qizil'), ('Yashil', 'Yashil'), ('Qora', 'Qora'), ('Ko`k', 'Ko`k'), ('Oq', 'Oq')], max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_season',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Winter', 'Qishki'), ('Summer', 'Yozgi'), ('Fall', 'Kuzgi'), ('Spring', 'Bahorgi'), ('FandS', 'Kuzgi va bahorgi')], max_length=31),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=15),
        ),
    ]
