# Generated by Django 3.2.8 on 2021-10-24 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0038_auto_20211024_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
    ]
