# Generated by Django 3.2.8 on 2021-10-24 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0039_remove_notes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
