# Generated by Django 3.2.8 on 2021-10-24 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0043_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='note_text',
        ),
    ]
