# Generated by Django 3.2.8 on 2021-10-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0045_notes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
    ]
