# Generated by Django 3.2.8 on 2021-10-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0047_auto_20211025_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Product name', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
