# Generated by Django 3.2.8 on 2021-10-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0048_auto_20211025_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, default='Product name', max_length=200, null=True),
        ),
    ]
