# Generated by Django 3.2.8 on 2021-10-25 04:34

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0050_remove_product_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[1000, 1000], upload_to='images'),
            preserve_default=False,
        ),
    ]
