# Generated by Django 3.2.8 on 2021-10-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0053_alter_product_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
