# Generated by Django 3.2.8 on 2021-10-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0057_product_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Countries',
        ),
    ]
