# Generated by Django 3.2.8 on 2021-10-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0058_remove_product_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Countries',
            field=models.CharField(choices=[('AUT', 'Austria'), ('DEU', 'Germany'), ('NLD', 'Neitherlands')], default=('AUT', 'Austria'), max_length=100),
        ),
    ]
