# Generated by Django 3.2.8 on 2021-10-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0059_product_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Countries',
        ),
    ]
