# Generated by Django 3.2.8 on 2021-10-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0062_alter_product_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='product_price_initial',
        ),
        migrations.AddField(
            model_name='product',
            name='product_price_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price_told',
            field=models.IntegerField(default=0),
        ),
    ]
