# Generated by Django 3.2.8 on 2021-10-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0063_auto_20211030_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sold_count',
            field=models.IntegerField(default=0),
        ),
    ]
