# Generated by Django 3.2.8 on 2021-10-31 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0065_auto_20211031_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsold',
            name='product_sold_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mnotes.product'),
        ),
    ]
