# Generated by Django 3.2.8 on 2021-10-31 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mnotes', '0067_remove_productsold_product_sold_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsold',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
