# Generated by Django 3.2.8 on 2021-11-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0072_remove_productsold_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsold',
            name='product_sold_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
