# Generated by Django 3.2.8 on 2021-11-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0074_alter_productsold_product_sold_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsold',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
