# Generated by Django 3.2.8 on 2021-11-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0076_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Nomi', max_length=200)),
                ('product_price', models.IntegerField()),
                ('owner_phone', models.IntegerField()),
                ('owner_name', models.CharField(default='Qarz oluvchi', max_length=200)),
                ('given_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
