# Generated by Django 3.2.8 on 2021-11-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0079_alter_debts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isdebt',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debts',
            name='owner_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='debts',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
