# Generated by Django 3.2.8 on 2021-11-09 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mnotes', '0080_auto_20211109_0014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debts',
            new_name='SellOnDebt',
        ),
        migrations.CreateModel(
            name='BuyOnDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_count', models.IntegerField(default=0)),
                ('product_price', models.IntegerField(default=0)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_phone', models.IntegerField(default=0)),
                ('date_bought', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
