# Generated by Django 3.2.8 on 2021-11-09 13:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0081_auto_20211109_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isdebt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=15, null=True),
        ),
    ]
