# Generated by Django 3.2.8 on 2021-11-09 13:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0082_auto_20211109_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Qizil', 'Qizil'), ('Yashil', 'Yashil'), ('Qora', 'Qora'), ('Ko`k', 'Ko`k'), ('Oq', 'Oq')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_season',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Winter', 'Qishki'), ('Summer', 'Yozgi'), ('Fall', 'Kuzgi'), ('Spring', 'Bahorgi'), ('FandS', 'Kuzgi va bahorgi')], max_length=31, null=True),
        ),
    ]
