# Generated by Django 3.2.8 on 2021-11-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0083_auto_20211109_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isdebt',
            field=models.BooleanField(default=False),
        ),
    ]
