# Generated by Django 3.2.8 on 2021-11-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0085_auto_20211109_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Mahsulot nomi', error_messages={'password_mismatch': 'Ikki xil parol kiritildi', 'required': 'Siz muhim ma`lumotlarni to`ldirmardingiz!', 'unique': 'Bu nom bilan akkount mavjud, boshqa nom tanlang'}, max_length=200),
        ),
    ]
