# Generated by Django 3.2.8 on 2021-11-10 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mnotes', '0089_productsold_isdebt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellondebt',
            old_name='owner_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='sellondebt',
            old_name='owner_phone',
            new_name='customer_phone',
        ),
        migrations.AlterField(
            model_name='sellondebt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
