# Generated by Django 3.2.8 on 2021-11-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0090_auto_20211110_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsold',
            name='isfullypaid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsold',
            name='ispartlypaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsold',
            name='left_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsold',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellondebt',
            name='product_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
