# Generated by Django 3.2.8 on 2021-11-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0002_auto_20211121_1825'),
        ('mnotes', '0091_auto_20211110_2042'),
    ]

    operations = [
    ]
