# Generated by Django 3.2.8 on 2021-11-10 22:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0091_auto_20211110_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyondebt',
            name='isfullypaid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buyondebt',
            name='ispartlypaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyondebt',
            name='left_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buyondebt',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Qizil', 'Qizil'), ('Yashil', 'Yashil'), ('Qora', 'Qora'), ('Ko`k', 'Ko`k'), ('Oq', 'Oq'), ('Jigarrang', 'Jigarrang'), ('Pushti', 'Pushti'), ('Kulrang', 'Kulrang'), ('Sariq', 'Sariq')], max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='sellondebt',
            name='customer_phone',
            field=models.IntegerField(blank=True),
        ),
    ]
