# Generated by Django 3.2.8 on 2021-11-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0093_auto_20211121_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_email', models.CharField(max_length=200)),
                ('vendor_tg', models.CharField(max_length=200)),
                ('vendor_phone_number', models.IntegerField(default=0)),
                ('store_name', models.CharField(max_length=200)),
                ('store_type', models.CharField(blank=True, choices=[('clothes', 'Kiyimlar'), ('shoes', 'Oyoq kiyim'), ('food', 'Oziq ovqat'), ('furniture', 'Mebel'), ('jewelry', 'Zargarlik'), ('cosmetics', 'Kosmetika'), ('stationery', 'Kanseleriya buyumlari'), ('underwear', 'Ichki kiyimlar'), ('others', 'Boshqa')], max_length=30, null=True)),
                ('store_website', models.CharField(max_length=200)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
