# Generated by Django 3.2.8 on 2021-11-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0094_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsold',
            name='isfullypaid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsold',
            name='ispartlypaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsold',
            name='left_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsold',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsold',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
