# Generated by Django 3.2.8 on 2021-11-21 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0096_productsold_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsold',
            name='date_sold',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
