# Generated by Django 3.2.8 on 2021-11-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0097_productsold_date_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='store_address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
