# Generated by Django 3.2.8 on 2021-11-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0099_vendor_vendor_insta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='store_type',
            field=models.CharField(blank=True, choices=[('Kiyimlar', 'Kiyimlar'), ('Oyoq kiyim', 'Oyoq kiyim'), ('Oziq ovqat', 'Oziq ovqat'), ('Mebel', 'Mebel'), ('Zargarlik', 'Zargarlik'), ('Kosmetika', 'Kosmetika'), ('Kanseleriya buyumlari', 'Kanseleriya buyumlari'), ('Ichki kiyimlar', 'Ichki kiyimlar'), ('Boshqa', 'Boshqa')], max_length=30, null=True),
        ),
    ]
