# Generated by Django 3.2.8 on 2021-11-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0101_alter_product_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='monthly_profit_aim',
            field=models.IntegerField(default=0),
        ),
    ]
