# Generated by Django 3.2.8 on 2021-11-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0103_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Mahsulot nomi', max_length=200),
        ),
    ]
