# Generated by Django 3.2.8 on 2021-11-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0104_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellondebt',
            name='customer_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
