# Generated by Django 3.2.8 on 2021-11-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0105_alter_sellondebt_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellondebt',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
