# Generated by Django 3.2.8 on 2021-11-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0106_sellondebt_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='monthly_profit_aim',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_phone_number',
            field=models.IntegerField(),
        ),
    ]
