# Generated by Django 3.2.8 on 2021-11-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0107_auto_20211125_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='monthly_profit_aim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
