# Generated by Django 3.2.8 on 2021-11-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0108_auto_20211125_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellondebt',
            name='soldproductid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buyondebt',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='product_sold_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='product_sold_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sellondebt',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellondebt',
            name='isfullypaid',
            field=models.BooleanField(default=False),
        ),
    ]
