# Generated by Django 3.2.8 on 2021-12-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0112_auto_20211203_0854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellOnDebt',
        ),
        migrations.AddField(
            model_name='productsold',
            name='customer_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsold',
            name='customer_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsold',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productsold',
            name='soldproductid',
            field=models.IntegerField(default=0),
        ),
    ]
