# Generated by Django 3.2.8 on 2021-12-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0113_auto_20211203_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
    ]
