# Generated by Django 3.2.8 on 2022-01-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0118_product_sold_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsold',
            name='soldproductid',
        ),
    ]
