# Generated by Django 3.2.8 on 2022-02-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0120_remove_productsold_product_sold_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productsold',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
