# Generated by Django 3.2.8 on 2022-02-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0123_rename_discount_date_product_last_discount_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_discount_date',
            field=models.DateTimeField(),
        ),
    ]
