# Generated by Django 3.2.8 on 2022-02-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0124_alter_product_last_discount_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_in_sum',
            field=models.IntegerField(default=0),
        ),
    ]
