# Generated by Django 3.2.8 on 2022-02-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0125_product_discount_in_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_discount_date',
            field=models.DateField(),
        ),
    ]
