# Generated by Django 3.2.8 on 2022-02-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0126_alter_product_last_discount_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_discount_date',
        ),
    ]
