# Generated by Django 3.2.8 on 2022-02-15 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0127_remove_product_last_discount_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_discount_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 19, 21, 15, 56823)),
            preserve_default=False,
        ),
    ]
