# Generated by Django 3.2.8 on 2022-02-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0128_product_last_discount_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='frayd_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='frayd_balance',
            field=models.IntegerField(default=0),
        ),
    ]
