# Generated by Django 3.2.8 on 2022-03-05 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0129_auto_20220227_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='frayd_balance',
            new_name='coin_balance',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='frayd_balance',
            new_name='coin_balance',
        ),
    ]
