# Generated by Django 4.0.6 on 2022-07-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0130_auto_20220305_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_discount_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
