# Generated by Django 4.0.6 on 2022-07-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0131_alter_product_last_discount_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='coin_balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
