# Generated by Django 4.0.6 on 2022-07-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0133_remove_vendor_coin_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyondebt',
            name='owner_phone',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
