# Generated by Django 4.0.6 on 2022-07-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0134_alter_buyondebt_owner_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='coin_balance',
        ),
    ]
