# Generated by Django 4.2 on 2023-04-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0135_remove_customer_coin_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_season',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_size',
        ),
    ]
