# Generated by Django 4.2 on 2023-05-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnotes', '0136_remove_product_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_insta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_tg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_insta',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_tg',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
